app = "smartbuddy-web"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "3000"

[build]
builder = "heroku/buildpacks:20"

[build.env]
NODE_ENV = "production"

[deploy]
release_command = "npm run build"
